language: python

python:
  - "2.6"
  - "2.7"

install:
  - pip install -r requirements_test.txt --use-mirrors

script:
  - coverage run --source=pangu setup.py test

after_success:
  - coveralls

notifications:
  email:
    - vinta.chen@gmail.com
